<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class AssessmentJawabanSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $assessment_jawaban = array(
            array('id' => '1', 'assessment_pertanyaan_id' => '1', 'jawaban' => 'Standar tidak menjadi acuan dalam penetapan visi, misi maupun operasional'),
            array('id' => '2', 'assessment_pertanyaan_id' => '1', 'jawaban' => 'Standar hanya digunakan operasional dalam bagian tertentu'),
            array('id' => '3', 'assessment_pertanyaan_id' => '1', 'jawaban' => 'Standar masih sebatas acuan dalam penetapan visi, misi dan tata nilai'),
            array('id' => '4', 'assessment_pertanyaan_id' => '1', 'jawaban' => 'Visi, misi dan tata nilai secara eksplisit mengacu kepada standar'),
            array('id' => '5', 'assessment_pertanyaan_id' => '2', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach terhadap masukan, proses dan keluaran dan disebarluaskan sebagian unit organisasi, dengan sebagian kecil aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '6', 'assessment_pertanyaan_id' => '2', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach terhadap masukan, proses dan keluaran dan disebarluaskan sebagian besar unit organisasi, dengan beberapa aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '7', 'assessment_pertanyaan_id' => '2', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach terhadap masukan, proses dan keluaran dan disebarluaskan hampir keseluruh unit organisasi, dengan sebagian besar aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '8', 'assessment_pertanyaan_id' => '2', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '9', 'assessment_pertanyaan_id' => '3', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '10', 'assessment_pertanyaan_id' => '3', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '11', 'assessment_pertanyaan_id' => '3', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '12', 'assessment_pertanyaan_id' => '3', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '13', 'assessment_pertanyaan_id' => '4', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '14', 'assessment_pertanyaan_id' => '4', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '15', 'assessment_pertanyaan_id' => '4', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '16', 'assessment_pertanyaan_id' => '4', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '17', 'assessment_pertanyaan_id' => '5', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '18', 'assessment_pertanyaan_id' => '5', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '19', 'assessment_pertanyaan_id' => '5', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '20', 'assessment_pertanyaan_id' => '5', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '21', 'assessment_pertanyaan_id' => '6', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '22', 'assessment_pertanyaan_id' => '6', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '23', 'assessment_pertanyaan_id' => '6', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '24', 'assessment_pertanyaan_id' => '6', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '25', 'assessment_pertanyaan_id' => '7', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '26', 'assessment_pertanyaan_id' => '7', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '27', 'assessment_pertanyaan_id' => '7', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '28', 'assessment_pertanyaan_id' => '7', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '29', 'assessment_pertanyaan_id' => '8', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '30', 'assessment_pertanyaan_id' => '8', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '31', 'assessment_pertanyaan_id' => '8', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '32', 'assessment_pertanyaan_id' => '8', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '33', 'assessment_pertanyaan_id' => '9', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '34', 'assessment_pertanyaan_id' => '9', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '35', 'assessment_pertanyaan_id' => '9', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '36', 'assessment_pertanyaan_id' => '9', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '37', 'assessment_pertanyaan_id' => '10', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '38', 'assessment_pertanyaan_id' => '10', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '39', 'assessment_pertanyaan_id' => '10', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '40', 'assessment_pertanyaan_id' => '10', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '41', 'assessment_pertanyaan_id' => '11', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '42', 'assessment_pertanyaan_id' => '11', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '43', 'assessment_pertanyaan_id' => '11', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '44', 'assessment_pertanyaan_id' => '11', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '45', 'assessment_pertanyaan_id' => '12', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '46', 'assessment_pertanyaan_id' => '12', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '47', 'assessment_pertanyaan_id' => '12', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
            array('id' => '48', 'assessment_pertanyaan_id' => '12', 'jawaban' => 'Ada penerapan pendekatan dan metode yang sesuai dengan tahapan pendekatan/approach untuk semua tingkatan dan disebarluaskan keseluruh unit organisasi, dengan keseluruhan semua aspek standardisasi dan penilaian kesesuaian'),
        );

        DB::table('assessment_jawaban')->insert($assessment_jawaban);
    }
}