<?php

namespace Database\Seeders;

// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;

class KotaSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $kota = [
            ['id' => '1101', 'kota' => 'ACEH SELATAN', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1102', 'kota' => 'ACEH TENGGARA', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1103', 'kota' => 'ACEH TIMUR', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1104', 'kota' => 'ACEH TENGAH', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1105', 'kota' => 'ACEH BARAT', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1106', 'kota' => 'ACEH BESAR', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1107', 'kota' => 'PIDIE', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1108', 'kota' => 'ACEH UTARA', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1109', 'kota' => 'SIMEULUE', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1110', 'kota' => 'ACEH SINGKIL', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1111', 'kota' => 'BIREUEN', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1112', 'kota' => 'ACEH BARAT DAYA', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1113', 'kota' => 'GAYO LUES', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1114', 'kota' => 'ACEH JAYA', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1115', 'kota' => 'NAGAN RAYA', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1116', 'kota' => 'ACEH TAMIANG', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1117', 'kota' => 'BENER MERIAH', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1118', 'kota' => 'PIDIE JAYA', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1171', 'kota' => 'KOTA BANDA ACEH', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1172', 'kota' => 'KOTA SABANG', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1173', 'kota' => 'KOTA LHOKSEUMAWE', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1174', 'kota' => 'KOTA LANGSA', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1175', 'kota' => 'KOTA SUBULUSSALAM', 'propinsi_id' => '11', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1201', 'kota' => 'TAPANULI TENGAH', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1202', 'kota' => 'TAPANULI UTARA', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1203', 'kota' => 'TAPANULI SELATAN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1204', 'kota' => 'NIAS', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1205', 'kota' => 'LANGKAT', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1206', 'kota' => 'KARO', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1207', 'kota' => 'DELI SERDANG', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1208', 'kota' => 'SIMALUNGUN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1209', 'kota' => 'ASAHAN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1210', 'kota' => 'LABUHANBATU', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1211', 'kota' => 'DAIRI', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1212', 'kota' => 'TOBA SAMOSIR', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1213', 'kota' => 'MANDAILING NATAL', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1214', 'kota' => 'NIAS SELATAN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1215', 'kota' => 'PAKPAK BHARAT', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1216', 'kota' => 'HUMBANG HASUNDUTAN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1217', 'kota' => 'SAMOSIR', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1218', 'kota' => 'SERDANG BEDAGAI', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1219', 'kota' => 'BATU BARA', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1220', 'kota' => 'PADANG LAWAS UTARA', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1221', 'kota' => 'PADANG LAWAS', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1222', 'kota' => 'LABUHANBATU SELATAN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1223', 'kota' => 'LABUHANBATU UTARA', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1224', 'kota' => 'NIAS UTARA', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1225', 'kota' => 'NIAS BARAT', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1271', 'kota' => 'KOTA MEDAN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1272', 'kota' => 'KOTA PEMATANG SIANTAR', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1273', 'kota' => 'KOTA SIBOLGA', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1274', 'kota' => 'KOTA TANJUNG BALAI', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1275', 'kota' => 'KOTA BINJAI', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1276', 'kota' => 'KOTA TEBING TINGGI', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1277', 'kota' => 'KOTA PADANGSIDIMPUAN', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1278', 'kota' => 'KOTA GUNUNGSITOLI', 'propinsi_id' => '12', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1301', 'kota' => 'PESISIR SELATAN', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1302', 'kota' => 'SOLOK', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1303', 'kota' => 'SIJUNJUNG', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1304', 'kota' => 'TANAH DATAR', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1305', 'kota' => 'PADANG PARIAMAN', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1306', 'kota' => 'AGAM', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1307', 'kota' => 'LIMA PULUH KOTA', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1308', 'kota' => 'PASAMAN', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1309', 'kota' => 'KEPULAUAN MENTAWAI', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1310', 'kota' => 'DHARMASRAYA', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1311', 'kota' => 'SOLOK SELATAN', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1312', 'kota' => 'PASAMAN BARAT', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1371', 'kota' => 'KOTA PADANG', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1372', 'kota' => 'KOTA SOLOK', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1373', 'kota' => 'KOTA SAWAHLUNTO', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1374', 'kota' => 'KOTA PADANG PANJANG', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1375', 'kota' => 'KOTA BUKITTINGGI', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1376', 'kota' => 'KOTA PAYAKUMBUH', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1377', 'kota' => 'KOTA PARIAMAN', 'propinsi_id' => '13', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1401', 'kota' => 'KAMPAR', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1402', 'kota' => 'INDRAGIRI HULU', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1403', 'kota' => 'BENGKALIS', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1404', 'kota' => 'INDRAGIRI HILIR', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1405', 'kota' => 'PELALAWAN', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1406', 'kota' => 'ROKAN HULU', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1407', 'kota' => 'ROKAN HILIR', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1408', 'kota' => 'SIAK', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1409', 'kota' => 'KUANTAN SINGINGI', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1410', 'kota' => 'KEPULAUAN MERANTI', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1471', 'kota' => 'KOTA PEKANBARU', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1472', 'kota' => 'KOTA DUMAI', 'propinsi_id' => '14', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1501', 'kota' => 'KERINCI', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1502', 'kota' => 'MERANGIN', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1503', 'kota' => 'SAROLANGUN', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1504', 'kota' => 'BATANGHARI', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1505', 'kota' => 'MUARO JAMBI', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1506', 'kota' => 'TANJUNG JABUNG BARAT', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1507', 'kota' => 'TANJUNG JABUNG TIMUR', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1508', 'kota' => 'BUNGO', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1509', 'kota' => 'TEBO', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1571', 'kota' => 'KOTA JAMBI', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1572', 'kota' => 'KOTA SUNGAI PENUH', 'propinsi_id' => '15', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1601', 'kota' => 'OGAN KOMERING ULU', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1602', 'kota' => 'OGAN KOMERING ILIR', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1603', 'kota' => 'MUARA ENIM', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1604', 'kota' => 'LAHAT', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1605', 'kota' => 'MUSI RAWAS', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1606', 'kota' => 'MUSI BANYUASIN', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1607', 'kota' => 'BANYUASIN', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1608', 'kota' => 'OGAN KOMERING ULU TIMUR', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1609', 'kota' => 'OGAN KOMERING ULU SELATAN', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1610', 'kota' => 'OGAN ILIR', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1611', 'kota' => 'EMPAT LAWANG', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1612', 'kota' => 'PENUKAL ABAB LEMATANG ILIR', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1613', 'kota' => 'MUSI RAWAS UTARA', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1671', 'kota' => 'KOTA PALEMBANG', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1672', 'kota' => 'KOTA PAGAR ALAM', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1673', 'kota' => 'KOTA LUBUK LINGGAU', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1674', 'kota' => 'KOTA PRABUMULIH', 'propinsi_id' => '16', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1701', 'kota' => 'BENGKULU SELATAN', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1702', 'kota' => 'REJANG LEBONG', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1703', 'kota' => 'BENGKULU UTARA', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1704', 'kota' => 'KAUR', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1705', 'kota' => 'SELUMA', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1706', 'kota' => 'MUKO MUKO', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1707', 'kota' => 'LEBONG', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1708', 'kota' => 'KEPAHIANG', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1709', 'kota' => 'BENGKULU TENGAH', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1771', 'kota' => 'KOTA BENGKULU', 'propinsi_id' => '17', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1801', 'kota' => 'LAMPUNG SELATAN', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1802', 'kota' => 'LAMPUNG TENGAH', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1803', 'kota' => 'LAMPUNG UTARA', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1804', 'kota' => 'LAMPUNG BARAT', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1805', 'kota' => 'TULANG BAWANG', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1806', 'kota' => 'TANGGAMUS', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1807', 'kota' => 'LAMPUNG TIMUR', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1808', 'kota' => 'WAY KANAN', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1809', 'kota' => 'PESAWARAN', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1810', 'kota' => 'PRINGSEWU', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1811', 'kota' => 'MESUJI', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1812', 'kota' => 'TULANG BAWANG BARAT', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1813', 'kota' => 'PESISIR BARAT', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1871', 'kota' => 'KOTA BANDAR LAMPUNG', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1872', 'kota' => 'KOTA METRO', 'propinsi_id' => '18', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1901', 'kota' => 'BANGKA', 'propinsi_id' => '19', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1902', 'kota' => 'BELITUNG', 'propinsi_id' => '19', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1903', 'kota' => 'BANGKA SELATAN', 'propinsi_id' => '19', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1904', 'kota' => 'BANGKA TENGAH', 'propinsi_id' => '19', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1905', 'kota' => 'BANGKA BARAT', 'propinsi_id' => '19', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1906', 'kota' => 'BELITUNG TIMUR', 'propinsi_id' => '19', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '1971', 'kota' => 'KOTA PANGKAL PINANG', 'propinsi_id' => '19', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '2101', 'kota' => 'BINTAN', 'propinsi_id' => '21', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '2102', 'kota' => 'KARIMUN', 'propinsi_id' => '21', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '2103', 'kota' => 'NATUNA', 'propinsi_id' => '21', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '2104', 'kota' => 'LINGGA', 'propinsi_id' => '21', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '2105', 'kota' => 'KEPULAUAN ANAMBAS', 'propinsi_id' => '21', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '2171', 'kota' => 'KOTA BATAM', 'propinsi_id' => '21', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '2172', 'kota' => 'KOTA TANJUNG PINANG', 'propinsi_id' => '21', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3101', 'kota' => 'ADM. KEP. SERIBU', 'propinsi_id' => '31', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3171', 'kota' => 'KOTA ADM. JAKARTA PUSAT', 'propinsi_id' => '31', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3172', 'kota' => 'KOTA ADM. JAKARTA UTARA', 'propinsi_id' => '31', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3173', 'kota' => 'KOTA ADM. JAKARTA BARAT', 'propinsi_id' => '31', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3174', 'kota' => 'KOTA ADM. JAKARTA SELATAN', 'propinsi_id' => '31', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3175', 'kota' => 'KOTA ADM. JAKARTA TIMUR', 'propinsi_id' => '31', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3201', 'kota' => 'BOGOR', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3202', 'kota' => 'SUKABUMI', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3203', 'kota' => 'CIANJUR', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3204', 'kota' => 'BANDUNG', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3205', 'kota' => 'GARUT', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3206', 'kota' => 'TASIKMALAYA', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3207', 'kota' => 'CIAMIS', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3208', 'kota' => 'KUNINGAN', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3209', 'kota' => 'CIREBON', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3210', 'kota' => 'MAJALENGKA', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3211', 'kota' => 'SUMEDANG', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3212', 'kota' => 'INDRAMAYU', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3213', 'kota' => 'SUBANG', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3214', 'kota' => 'PURWAKARTA', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3215', 'kota' => 'KARAWANG', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3216', 'kota' => 'BEKASI', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3217', 'kota' => 'BANDUNG BARAT', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3218', 'kota' => 'PANGANDARAN', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3271', 'kota' => 'KOTA BOGOR', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3272', 'kota' => 'KOTA SUKABUMI', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3273', 'kota' => 'KOTA BANDUNG', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3274', 'kota' => 'KOTA CIREBON', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3275', 'kota' => 'KOTA BEKASI', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3276', 'kota' => 'KOTA DEPOK', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3277', 'kota' => 'KOTA CIMAHI', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3278', 'kota' => 'KOTA TASIKMALAYA', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3279', 'kota' => 'KOTA BANJAR', 'propinsi_id' => '32', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3301', 'kota' => 'CILACAP', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3302', 'kota' => 'BANYUMAS', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3303', 'kota' => 'PURBALINGGA', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3304', 'kota' => 'BANJARNEGARA', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3305', 'kota' => 'KEBUMEN', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3306', 'kota' => 'PURWOREJO', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3307', 'kota' => 'WONOSOBO', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3308', 'kota' => 'MAGELANG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3309', 'kota' => 'BOYOLALI', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3310', 'kota' => 'KLATEN', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3311', 'kota' => 'SUKOHARJO', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3312', 'kota' => 'WONOGIRI', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3313', 'kota' => 'KARANGANYAR', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3314', 'kota' => 'SRAGEN', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3315', 'kota' => 'GROBOGAN', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3316', 'kota' => 'BLORA', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3317', 'kota' => 'REMBANG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3318', 'kota' => 'PATI', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3319', 'kota' => 'KUDUS', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3320', 'kota' => 'JEPARA', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3321', 'kota' => 'DEMAK', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3322', 'kota' => 'SEMARANG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3323', 'kota' => 'TEMANGGUNG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3324', 'kota' => 'KENDAL', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3325', 'kota' => 'BATANG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3326', 'kota' => 'PEKALONGAN', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3327', 'kota' => 'PEMALANG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3328', 'kota' => 'TEGAL', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3329', 'kota' => 'BREBES', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3371', 'kota' => 'KOTA MAGELANG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3372', 'kota' => 'KOTA SURAKARTA', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3373', 'kota' => 'KOTA SALATIGA', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3374', 'kota' => 'KOTA SEMARANG', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3375', 'kota' => 'KOTA PEKALONGAN', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3376', 'kota' => 'KOTA TEGAL', 'propinsi_id' => '33', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3401', 'kota' => 'KULON PROGO', 'propinsi_id' => '34', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3402', 'kota' => 'BANTUL', 'propinsi_id' => '34', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3403', 'kota' => 'GUNUNGKIDUL', 'propinsi_id' => '34', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3404', 'kota' => 'SLEMAN', 'propinsi_id' => '34', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3471', 'kota' => 'KOTA YOGYAKARTA', 'propinsi_id' => '34', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3501', 'kota' => 'PACITAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3502', 'kota' => 'PONOROGO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3503', 'kota' => 'TRENGGALEK', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3504', 'kota' => 'TULUNGAGUNG', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3505', 'kota' => 'BLITAR', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3506', 'kota' => 'KEDIRI', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3507', 'kota' => 'MALANG', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3508', 'kota' => 'LUMAJANG', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3509', 'kota' => 'JEMBER', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3510', 'kota' => 'BANYUWANGI', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3511', 'kota' => 'BONDOWOSO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3512', 'kota' => 'SITUBONDO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3513', 'kota' => 'PROBOLINGGO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3514', 'kota' => 'PASURUAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3515', 'kota' => 'SIDOARJO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3516', 'kota' => 'MOJOKERTO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3517', 'kota' => 'JOMBANG', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3518', 'kota' => 'NGANJUK', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3519', 'kota' => 'MADIUN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3520', 'kota' => 'MAGETAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3521', 'kota' => 'NGAWI', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3522', 'kota' => 'BOJONEGORO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3523', 'kota' => 'TUBAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3524', 'kota' => 'LAMONGAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3525', 'kota' => 'GRESIK', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3526', 'kota' => 'BANGKALAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3527', 'kota' => 'SAMPANG', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3528', 'kota' => 'PAMEKASAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3529', 'kota' => 'SUMENEP', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3571', 'kota' => 'KOTA KEDIRI', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3572', 'kota' => 'KOTA BLITAR', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3573', 'kota' => 'KOTA MALANG', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3574', 'kota' => 'KOTA PROBOLINGGO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3575', 'kota' => 'KOTA PASURUAN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3576', 'kota' => 'KOTA MOJOKERTO', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3577', 'kota' => 'KOTA MADIUN', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3578', 'kota' => 'KOTA SURABAYA', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3579', 'kota' => 'KOTA BATU', 'propinsi_id' => '35', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3601', 'kota' => 'PANDEGLANG', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3602', 'kota' => 'LEBAK', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3603', 'kota' => 'TANGERANG', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3604', 'kota' => 'SERANG', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3671', 'kota' => 'KOTA TANGERANG', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3672', 'kota' => 'KOTA CILEGON', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3673', 'kota' => 'KOTA SERANG', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '3674', 'kota' => 'KOTA TANGERANG SELATAN', 'propinsi_id' => '36', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5101', 'kota' => 'JEMBRANA', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5102', 'kota' => 'TABANAN', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5103', 'kota' => 'BADUNG', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5104', 'kota' => 'GIANYAR', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5105', 'kota' => 'KLUNGKUNG', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5106', 'kota' => 'BANGLI', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5107', 'kota' => 'KARANGASEM', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5108', 'kota' => 'BULELENG', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5171', 'kota' => 'KOTA DENPASAR', 'propinsi_id' => '51', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5201', 'kota' => 'LOMBOK BARAT', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5202', 'kota' => 'LOMBOK TENGAH', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5203', 'kota' => 'LOMBOK TIMUR', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5204', 'kota' => 'SUMBAWA', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5205', 'kota' => 'DOMPU', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5206', 'kota' => 'BIMA', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5207', 'kota' => 'SUMBAWA BARAT', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5208', 'kota' => 'LOMBOK UTARA', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5271', 'kota' => 'KOTA MATARAM', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5272', 'kota' => 'KOTA BIMA', 'propinsi_id' => '52', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5301', 'kota' => 'KUPANG', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5302', 'kota' => 'TIMOR TENGAH SELATAN', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5303', 'kota' => 'TIMOR TENGAH UTARA', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5304', 'kota' => 'BELU', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5305', 'kota' => 'ALOR', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5306', 'kota' => 'FLORES TIMUR', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5307', 'kota' => 'SIKKA', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5308', 'kota' => 'ENDE', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5309', 'kota' => 'NGADA', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5310', 'kota' => 'MANGGARAI', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5311', 'kota' => 'SUMBA TIMUR', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5312', 'kota' => 'SUMBA BARAT', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5313', 'kota' => 'LEMBATA', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5314', 'kota' => 'ROTE NDAO', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5315', 'kota' => 'MANGGARAI BARAT', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5316', 'kota' => 'NAGEKEO', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5317', 'kota' => 'SUMBA TENGAH', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5318', 'kota' => 'SUMBA BARAT DAYA', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5319', 'kota' => 'MANGGARAI TIMUR', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5320', 'kota' => 'SABU RAIJUA', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5321', 'kota' => 'MALAKA', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '5371', 'kota' => 'KOTA KUPANG', 'propinsi_id' => '53', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6101', 'kota' => 'SAMBAS', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6102', 'kota' => 'MEMPAWAH', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6103', 'kota' => 'SANGGAU', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6104', 'kota' => 'KETAPANG', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6105', 'kota' => 'SINTANG', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6106', 'kota' => 'KAPUAS HULU', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6107', 'kota' => 'BENGKAYANG', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6108', 'kota' => 'LANDAK', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6109', 'kota' => 'SEKADAU', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6110', 'kota' => 'MELAWI', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6111', 'kota' => 'KAYONG UTARA', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6112', 'kota' => 'KUBU RAYA', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6171', 'kota' => 'KOTA PONTIANAK', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6172', 'kota' => 'KOTA SINGKAWANG', 'propinsi_id' => '61', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6201', 'kota' => 'KOTAWARINGIN BARAT', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6202', 'kota' => 'KOTAWARINGIN TIMUR', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6203', 'kota' => 'KAPUAS', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6204', 'kota' => 'BARITO SELATAN', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6205', 'kota' => 'BARITO UTARA', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6206', 'kota' => 'KATINGAN', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6207', 'kota' => 'SERUYAN', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6208', 'kota' => 'SUKAMARA', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6209', 'kota' => 'LAMANDAU', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6210', 'kota' => 'GUNUNG MAS', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6211', 'kota' => 'PULANG PISAU', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6212', 'kota' => 'MURUNG RAYA', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6213', 'kota' => 'BARITO TIMUR', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6271', 'kota' => 'KOTA PALANGKARAYA', 'propinsi_id' => '62', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6301', 'kota' => 'TANAH LAUT', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6302', 'kota' => 'KOTABARU', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6303', 'kota' => 'BANJAR', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6304', 'kota' => 'BARITO KUALA', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6305', 'kota' => 'TAPIN', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6306', 'kota' => 'HULU SUNGAI SELATAN', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6307', 'kota' => 'HULU SUNGAI TENGAH', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6308', 'kota' => 'HULU SUNGAI UTARA', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6309', 'kota' => 'TABALONG', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6310', 'kota' => 'TANAH BUMBU', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6311', 'kota' => 'BALANGAN', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6371', 'kota' => 'KOTA BANJARMASIN', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6372', 'kota' => 'KOTA BANJARBARU', 'propinsi_id' => '63', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6401', 'kota' => 'PASER', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6402', 'kota' => 'KUTAI KARTANEGARA', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6403', 'kota' => 'BERAU', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6407', 'kota' => 'KUTAI BARAT', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6408', 'kota' => 'KUTAI TIMUR', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6409', 'kota' => 'PENAJAM PASER UTARA', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6411', 'kota' => 'MAHAKAM ULU', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6471', 'kota' => 'KOTA BALIKPAPAN', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6472', 'kota' => 'KOTA SAMARINDA', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6474', 'kota' => 'KOTA BONTANG', 'propinsi_id' => '64', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6501', 'kota' => 'BULUNGAN', 'propinsi_id' => '65', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6502', 'kota' => 'MALINAU', 'propinsi_id' => '65', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6503', 'kota' => 'NUNUKAN', 'propinsi_id' => '65', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6504', 'kota' => 'TANA TIDUNG', 'propinsi_id' => '65', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '6571', 'kota' => 'KOTA TARAKAN', 'propinsi_id' => '65', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7101', 'kota' => 'BOLAANG MONGONDOW', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7102', 'kota' => 'MINAHASA', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7103', 'kota' => 'KEPULAUAN SANGIHE', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7104', 'kota' => 'KEPULAUAN TALAUD', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7105', 'kota' => 'MINAHASA SELATAN', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7106', 'kota' => 'MINAHASA UTARA', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7107', 'kota' => 'MINAHASA TENGGARA', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7108', 'kota' => 'BOLAANG MONGONDOW UTARA', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7109', 'kota' => 'KEP. SIAU TAGULANDANG BIARO', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7110', 'kota' => 'BOLAANG MONGONDOW TIMUR', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7111', 'kota' => 'BOLAANG MONGONDOW SELATAN', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7171', 'kota' => 'KOTA MANADO', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7172', 'kota' => 'KOTA BITUNG', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7173', 'kota' => 'KOTA TOMOHON', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7174', 'kota' => 'KOTA KOTAMOBAGU', 'propinsi_id' => '71', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7201', 'kota' => 'BANGGAI', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7202', 'kota' => 'POSO', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7203', 'kota' => 'DONGGALA', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7204', 'kota' => 'TOLI TOLI', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7205', 'kota' => 'BUOL', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7206', 'kota' => 'MOROWALI', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7207', 'kota' => 'BANGGAI KEPULAUAN', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7208', 'kota' => 'PARIGI MOUTONG', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7209', 'kota' => 'TOJO UNA UNA', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7210', 'kota' => 'SIGI', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7211', 'kota' => 'BANGGAI LAUT', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7212', 'kota' => 'MOROWALI UTARA', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7271', 'kota' => 'KOTA PALU', 'propinsi_id' => '72', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7301', 'kota' => 'KEPULAUAN SELAYAR', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7302', 'kota' => 'BULUKUMBA', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7303', 'kota' => 'BANTAENG', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7304', 'kota' => 'JENEPONTO', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7305', 'kota' => 'TAKALAR', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7306', 'kota' => 'GOWA', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7307', 'kota' => 'SINJAI', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7308', 'kota' => 'BONE', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7309', 'kota' => 'MAROS', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7310', 'kota' => 'PANGKAJENE KEPULAUAN', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7311', 'kota' => 'BARRU', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7312', 'kota' => 'SOPPENG', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7313', 'kota' => 'WAJO', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7314', 'kota' => 'SIDENRENG RAPPANG', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7315', 'kota' => 'PINRANG', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7316', 'kota' => 'ENREKANG', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7317', 'kota' => 'LUWU', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7318', 'kota' => 'TANA TORAJA', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7322', 'kota' => 'LUWU UTARA', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7324', 'kota' => 'LUWU TIMUR', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7326', 'kota' => 'TORAJA UTARA', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7371', 'kota' => 'KOTA MAKASSAR', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7372', 'kota' => 'KOTA PARE PARE', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7373', 'kota' => 'KOTA PALOPO', 'propinsi_id' => '73', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7401', 'kota' => 'KOLAKA', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7402', 'kota' => 'KONAWE', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7403', 'kota' => 'MUNA', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7404', 'kota' => 'BUTON', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7405', 'kota' => 'KONAWE SELATAN', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7406', 'kota' => 'BOMBANA', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7407', 'kota' => 'WAKATOBI', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7408', 'kota' => 'KOLAKA UTARA', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7409', 'kota' => 'KONAWE UTARA', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7410', 'kota' => 'BUTON UTARA', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7411', 'kota' => 'KOLAKA TIMUR', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7412', 'kota' => 'KONAWE KEPULAUAN', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7413', 'kota' => 'MUNA BARAT', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7414', 'kota' => 'BUTON TENGAH', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7415', 'kota' => 'BUTON SELATAN', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7471', 'kota' => 'KOTA KENDARI', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7472', 'kota' => 'KOTA BAU BAU', 'propinsi_id' => '74', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7501', 'kota' => 'GORONTALO', 'propinsi_id' => '75', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7502', 'kota' => 'BOALEMO', 'propinsi_id' => '75', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7503', 'kota' => 'BONE BOLANGO', 'propinsi_id' => '75', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7504', 'kota' => 'PAHUWATO', 'propinsi_id' => '75', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7505', 'kota' => 'GORONTALO UTARA', 'propinsi_id' => '75', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7571', 'kota' => 'KOTA GORONTALO', 'propinsi_id' => '75', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7601', 'kota' => 'MAMUJU UTARA', 'propinsi_id' => '76', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7602', 'kota' => 'MAMUJU', 'propinsi_id' => '76', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7603', 'kota' => 'MAMASA', 'propinsi_id' => '76', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7604', 'kota' => 'POLEWALI MANDAR', 'propinsi_id' => '76', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7605', 'kota' => 'MAJENE', 'propinsi_id' => '76', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '7606', 'kota' => 'MAMUJU TENGAH', 'propinsi_id' => '76', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8101', 'kota' => 'MALUKU TENGAH', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8102', 'kota' => 'MALUKU TENGGARA', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8103', 'kota' => 'MALUKU TENGGARA BARAT', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8104', 'kota' => 'BURU', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8105', 'kota' => 'SERAM BAGIAN TIMUR', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8106', 'kota' => 'SERAM BAGIAN BARAT', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8107', 'kota' => 'KEPULAUAN ARU', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8108', 'kota' => 'MALUKU BARAT DAYA', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8109', 'kota' => 'BURU SELATAN', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8171', 'kota' => 'KOTA AMBON', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8172', 'kota' => 'KOTA TUAL', 'propinsi_id' => '81', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8201', 'kota' => 'HALMAHERA BARAT', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8202', 'kota' => 'HALMAHERA TENGAH', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8203', 'kota' => 'HALMAHERA UTARA', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8204', 'kota' => 'HALMAHERA SELATAN', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8205', 'kota' => 'KEPULAUAN SULA', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8206', 'kota' => 'HALMAHERA TIMUR', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8207', 'kota' => 'PULAU MOROTAI', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8208', 'kota' => 'PULAU TALIABU', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8271', 'kota' => 'KOTA TERNATE', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '8272', 'kota' => 'KOTA TIDORE KEPULAUAN', 'propinsi_id' => '82', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9101', 'kota' => 'MERAUKE', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9102', 'kota' => 'JAYAWIJAYA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9103', 'kota' => 'JAYAPURA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9104', 'kota' => 'NABIRE', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9105', 'kota' => 'KEPULAUAN YAPEN', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9106', 'kota' => 'BIAK NUMFOR', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9107', 'kota' => 'PUNCAK JAYA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9108', 'kota' => 'PANIAI', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9109', 'kota' => 'MIMIKA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9110', 'kota' => 'SARMI', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9111', 'kota' => 'KEEROM', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9112', 'kota' => 'PEGUNUNGAN BINTANG', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9113', 'kota' => 'YAHUKIMO', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9114', 'kota' => 'TOLIKARA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9115', 'kota' => 'WAROPEN', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9116', 'kota' => 'BOVEN DIGOEL', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9117', 'kota' => 'MAPPI', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9118', 'kota' => 'ASMAT', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9119', 'kota' => 'SUPIORI', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9120', 'kota' => 'MAMBERAMO RAYA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9121', 'kota' => 'MAMBERAMO TENGAH', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9122', 'kota' => 'YALIMO', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9123', 'kota' => 'LANNY JAYA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9124', 'kota' => 'NDUGA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9125', 'kota' => 'PUNCAK', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9126', 'kota' => 'DOGIYAI', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9127', 'kota' => 'INTAN JAYA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9128', 'kota' => 'DEIYAI', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9171', 'kota' => 'KOTA JAYAPURA', 'propinsi_id' => '91', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9201', 'kota' => 'SORONG', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9202', 'kota' => 'MANOKWARI', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9203', 'kota' => 'FAK FAK', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9204', 'kota' => 'SORONG SELATAN', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9205', 'kota' => 'RAJA AMPAT', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9206', 'kota' => 'TELUK BINTUNI', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9207', 'kota' => 'TELUK WONDAMA', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9208', 'kota' => 'KAIMANA', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9209', 'kota' => 'TAMBRAUW', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9210', 'kota' => 'MAYBRAT', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9211', 'kota' => 'MANOKWARI SELATAN', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9212', 'kota' => 'PEGUNUNGAN ARFAK', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')],
            ['id' => '9271', 'kota' => 'KOTA SORONG', 'propinsi_id' => '92', 'created_at' => date('Y-m-d H:i:s'), 'updated_at' => date('Y-m-d H:i:s')]
        ];

        DB::table('kota')->insert($kota);
    }
}